apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  aws_access_key_id: QVNJQVgzSE02TFpMTlNIV1JOTU0K
  aws_secret_access_key: Q3pLMVNHU090ZVFXd2JIQU9WWXgyY0tZdHJmVjNCeGw3NytIZ1EzOQo=
  aws_session_token: RndvR1pYSXZZWGR6RUZBYURGUHdRSHZNZ2dpZkp2enpqQ0xWQWU2RHhPU2lwdFdPZmlTemJtd3NKd05pQWZEN3Nxb2ZtSGpFbEdHaVJwZG1TK2ozajF2WHlJdXBGdS9BUndlbmppRnE0NnVkOFpiZmtHUUp6TFJ4dmlJYk5RaDdyUEQ3dnNvU01xeVVQVWliQXhnMVdkZi9RQnZKem8zdGwrWStxeEZNOTczTkloN3lrSFRYOTJtaUZDWG9NeUhwUnMyQThaSlhKQ3JkTkEyTUpyQWVVMS9lc1dOVUtPTktqKzBaUytrTjgvLy93TG83OEExQWIyRDZNLzJRbGVnb2hLeXVDR1djVWt2L2RkbmFDMTFyOGVkd1RXUzBST0NXVVhtYjRPZ2tOYURwYnNZdVhwVXlqOTRoK3VUTjg1Y2JzaWlzanNXWkJqSXRjaWh1YlFBM0hWMzRmU1dORUVra0EvRGVVNlNsUHNWYUsxUjBvUjlCWnRGalh5aEFhM0p3WVg3Wm15YWQK