# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - run: docker build -t udagram-api-feed ./udagram-api-feed
    - run: docker build -t udagram-api-user ./udagram-api-user
    - run: docker build -t udagram-frontend ./udagram-frontend
    - run: docker build -t reverseproxy ./udagram-reverseproxy 
    - uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: docker tag udagram-api-feed abdi123/udagram-api-feed:v5
    - run: docker tag udagram-api-user abdi123/udagram-api-user:v5
    - run: docker tag udagram-frontend abdi123/udagram-frontend:v5    
    - run: docker tag reverseproxy abdi123/reverseproxy:v5    
    - run: docker push abdi123/udagram-api-feed:v5  
    - run: docker push abdi123/udagram-api-user:v5 
    - run: docker push abdi123/udagram-frontend:v5
    - run: docker push abdi123/reverseproxy:v5    
